### ISSUE TITLE
None type on nslt_dataset.py", line 59

### ISSUE THREAD

**Issue by celenaponce** [dxli94/WLASL#13]
I have downloaded all the data and gotten the missing data.  When I start running the nslt_100, I get the following error:

w, h, c = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

I made an if else statement to jump over these lines if success is false and also print out the file names.  Here is the list on the first part of the first epoch:
/content/drive/MyDrive/WLASL2000/WLASL2000/40841.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/40841.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/50046.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/50046.mp4
Epoch 1 train Loc Loss: 0.3859 Cls Loss: 0.4550 Tot Loss: 0.4204 Accu :0.0000
/content/drive/MyDrive/WLASL2000/WLASL2000/13642.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/22120.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/22120.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/49183.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/57641.mp4
Epoch 1 train Loc Loss: 0.0812 Cls Loss: 0.1002 Tot Loss: 0.0907 Accu :0.0083
/content/drive/MyDrive/WLASL2000/WLASL2000/64292.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/06839.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/69531.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/22121.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/22121.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/36937.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/63673.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/10158.mp4
Epoch 1 train Loc Loss: 0.0574 Cls Loss: 0.0588 Tot Loss: 0.0581 Accu :0.0111
/content/drive/MyDrive/WLASL2000/WLASL2000/57285.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/57285.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/49181.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/49181.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/50044.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/14894.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/14894.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/14894.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/56848.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/63208.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/62169.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/32955.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/05638.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/20986.mp4
Epoch 1 train Loc Loss: 0.0592 Cls Loss: 0.0572 Tot Loss: 0.0582 Accu :0.0083
/content/drive/MyDrive/WLASL2000/WLASL2000/64218.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/64218.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/14893.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/14893.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/57639.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/57639.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/57639.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/38533.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/53275.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/23776.mp4
Epoch 1 train Loc Loss: 0.0592 Cls Loss: 0.0563 Tot Loss: 0.0578 Accu :0.0067
/content/drive/MyDrive/WLASL2000/WLASL2000/64091.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/64219.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/14680.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/14680.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/69422.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/69238.mp4
Epoch 1 train Loc Loss: 0.0589 Cls Loss: 0.0570 Tot Loss: 0.0580 Accu :0.0083
/content/drive/MyDrive/WLASL2000/WLASL2000/34742.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/34742.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/34742.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/13702.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/36936.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/14681.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/14681.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/27216.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/27216.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/13213.mp4
/content/drive/MyDrive/WLASL2000/WLASL2000/69413.mp4

**Comment by dxli94** [comment]
Since you have acquired all the data, explanations could be you did not properly place the videos or configure the path to video folders. 

Quite sure this is not a problem in the implementation itself, so I am closing the issue.

**Comment by atheeraa** [comment]
@celenaponce Hello, I'm facing the same issue, were you able to solve it?
