### ISSUE TITLE
ERROR: Unexpected bus error encountered in worker.

### ISSUE THREAD

**Issue by CHI-YU-SUNG** [dxli94/WLASL#15]
Hello, when I try to run the train_i3d.py, it appear the following errors during the first epoch training
#######
...
Epoch 1 train Loc Loss: 0.0019 Cls Loss: 0.0009 Tot Loss: 0.0014 Accu :0.8119
Epoch 1 train Loc Loss: 0.0014 Cls Loss: 0.0006 Tot Loss: 0.0010 Accu :0.8121
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 511, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "/usr/local/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/usr/local/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/local/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/usr/local/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/usr/local/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 63, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 30920) is killed by signal: Bus error. 
######
It struggle me for long time and need some help, thanks

**Comment by CHI-YU-SUNG** [comment]
My GPU is RTX2070Ti, batch_size = 2 and the dataloader of pin_memory=false

**Comment by dxli94** [comment]
The error msg seems to me that the shared memory (shm) is limited.

Are you using a Docker container? If so, could you try increasing shm size?

Otherwise, could you refer to[ here](https://discuss.pytorch.org/t/training-crashes-due-to-insufficient-shared-memory-shm-nn-dataparallel/26396) for possible solutions?

**Comment by CHI-YU-SUNG** [comment]
Yes, I use docker container, maybe i should try to increasing my shm size. Thanks for your answer.

**Comment by dxli94** [comment]
I was using 1080 Ti with 12GB GPU memory back then. Using batch size = 2 is okay for training and I don't expect a significant gap in performance albeit possibly some. 

I just tried testing on my machine. The peak GPU memory was around 10 Gb. But I guess there might be CUDA caches you could empty to free some memory usage. Maybe you can look into it considering the GPU memory.

**Comment by CHI-YU-SUNG** [comment]
Thanks a lot. I try learning about it

**Comment by CHI-YU-SUNG** [comment]
Sorry , can I ask some question about the training process

1. I am not sure what is top 10 per class accuracy  line 133 in test_i3d.py file (below) means ? 
print('top-k average per class acc: {}, {}, {}'.format(top1_per_class, top5_per_class, top10_per_class))
Does that mean the highest video, which the average frames accuracy , in top ten classes?
2. When I tried to testing, which .pt file should I use in checkpoints folder because there are many .pt file in it 
3. Consider the training step, there are two different mode in it (rgb and flow), how should I concate these rgb and flow together like the model structure below 
4. which structure the code use? 

![111](https://user-images.githubusercontent.com/51199659/115866670-951c1180-a46c-11eb-979e-77752598a796.jpg)
![11](https://user-images.githubusercontent.com/51199659/115867024-1e334880-a46d-11eb-839a-ff9922766acf.jpg)
![1111](https://user-images.githubusercontent.com/51199659/115867080-3014eb80-a46d-11eb-8f2b-63c867c16c4b.jpg)
![1](https://user-images.githubusercontent.com/51199659/115867150-49b63300-a46d-11eb-80f3-d88b1cb40fe2.jpg)
