### ISSUE TITLE
Processed Videos Start and End Frames

### ISSUE THREAD

**Issue by ayush055** [dxli94/WLASL#16]
I noticed that for the Youtube videos where specific frames were being cut out, the processed video did not match the word. Looking into this issue, I noticed that the start and end frames in the JSON file did not match the same start and end frames in the video for the word (due to a different frame rate). For example, in this link: https://www.youtube.com/watch?v=F5Wef1_PtLk, the word "drink" is supposed to start at frame 5710 if the downloaded Youtube video is 25 fps. However, the downloaded youtube videos are 30 fps and the start and end frames need to be scaled accordingly (so it should start at frame 6852).

**Comment by dxli94** [comment]
Yes. This is documented in the README.

If you use the provided preprocessing script, this should not be an issue.
