### ISSUE TITLE
Video frame preprocess

### ISSUE THREAD

**Issue by chenyichun** [dxli94/WLASL#20]
Before doing data augmentation (random crop + random flip), is each frame a cropped image based on person bbox or the entire frame from the video?

**Comment by dxli94** [comment]
In our experiments, we feed entire frames. Yet you may try the alternative to feed bounding boxes, and we expect it to be working fine as well.

Please be reminded that we provide pre-processed videos on request to save your time downloading the data. You may check out the README and fill the data request form for access.

Thanks.

**Comment by chenyichun** [comment]
Thank you for replying so quickly. Based on my understanding for the paper, is it correct that you resize the frame according to the person bbox diagonal size first, and then do random crop on the entire frames? 

Also, although not related to this issue, would you release the training code for 2D Conv. RNN model and Pose RNN model? I try to reproduce the results on these two models but I am running to big mismatch and wondering what mistakes I have made. Really appreciate if you could release them.

**Comment by dxli94** [comment]
> is it correct that you resize the frame according to the person bbox diagonal size first, and then do random crop on the entire frames?

This is correct. However, please be advised that the resizing based on bbox is done offline. During training, only random cropping/flipping are used for augmentation.  

> would you release the training code for 2D Conv. RNN model and Pose RNN model? 

We've released TGCN and I3D models, which are better pose-based and RGB-based models in our experiments. We might release RCNN/RNN models but there is no guarantee. Yet, you may send mails to me for accessing those models.
