### ISSUE TITLE
Cant download all video!

### ISSUE THREAD

**Issue by LiangSiyv** [dxli94/WLASL#21]
I clone this project to my local environment and run the script. A large part of the videos is correctly downloaded. BUT there are still almost 10% of videos that couldn't be download. Eventually, I can download only 18,915 videos, which contain 1736 invalid .swf files.
e.g. 
ERROR:root: Unsuccessful downloading - youtube video url https://www.youtube.com/watch?v=YEFd7zsUNXU

plus: I tried many times.

**Comment by dxli94** [comment]
Please see README for requesting missing videos by filling in the Google form.
