### ISSUE TITLE
Test model not working due to config file

### ISSUE THREAD

**Issue by Enigma-I-am** [dxli94/WLASL#24]
I tried testing the pre-trained models downloaded from drive after installing all python tools and I keep getting this error

```Traceback (most recent call last):
  File "test_tgcn.py", line 101, in <module>
    configs = Config(config_file)
  File "/Users/mac/pythonstuff/WLASL-master/code/TGCN/configs.py", line 10, in __init__
    train_config = config['TRAIN']
  File "/usr/local/anaconda3/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'TRAIN'```

I don't think this is a major issue but I am very new to this field and I can't seem to understand what wrong. Please help

**Comment by Enigma-I-am** [comment]
I found what the problem was.

**Comment by dahburj** [comment]
May I ask what it was you did to solve it? Was getting the same error & almost felt like I made some progress until I came across this: 
`FileNotFoundError: [Errno 2] No such file or directory: 'code/Pose-GCN/posegcn/features/69092'
`
& I can't seem to wrap my head around what I'm missing.

**Comment by dxli94** [comment]
> May I ask what it was you did to solve it? Was getting the same error & almost felt like I made some progress until I came across this: `FileNotFoundError: [Errno 2] No such file or directory: 'code/Pose-GCN/posegcn/features/69092' ` & I can't seem to wrap my head around what I'm missing.

Have you properly downloaded and placed the 2d poses into the specified path?
