### ISSUE TITLE
About WLASL benchmarks

### ISSUE THREAD

**Issue by jackyjsy** [dxli94/WLASL#27]
Great repo and thanks for your effort on collecting such amazing dataset! 

I am trying to run SLR experiment on WLASL. Where can I find the newest benchmarks of WLASL 2000? I have checked [paperwithcode](https://paperswithcode.com/dataset/wlasl) and cannot find any benchmarks uploaded. Can I consider the results reported in the dataset [paper](https://arxiv.org/pdf/1910.11006.pdf) (Top-1 32.48, Top-5 57.31) as the state-of-the-art results?

**Comment by dxli94** [comment]
Hi Songyao,

You may take that for a comparison. I also suggest you check the following recent works.

"Transferring cross-domain knowledge for video sign language recognition"
"BSL-1K: Scaling up co-articulated sign language recognition using mouthing cues"
"Hand-Model-Aware Sign Language Recognition"

Dongxu

**Comment by jackyjsy** [comment]
Thank you very much!
