### ISSUE TITLE
missing videos

### ISSUE THREAD

**Issue by mks0601** [dxli94/WLASL#30]
Hi, I got a google drive link after submitting the misssing video list.
However, it seems all videos in the link are pre-processed to have 256x256 shape.
Could you let me know how bboxs should be changed to the 256x256 pre-processed videos?
Also, could you release missing videos of original resolutions?
Thanks!

**Comment by dxli94** [comment]
Dear Gyeongsik,

Sorry for the very late response. Unfortunately, we are not holding the original videos anymore. 

In practice, we did not find the pre-processing/bounding box extraction seems to create a large performance gap.

Dongxu
