### ISSUE TITLE
creating my own dataset

### ISSUE THREAD

**Issue by atheeraa** [dxli94/WLASL#34]
Hello, 

I'm trying to use my own dataset, 
can you please tell me how? 

I already have them in mp4 format, I placed them in the correct folder, changes the content of nslt_100.json to be : 
{"0000":{"subset": "train", "action": [ 0 ,1, 93 ]},
"0001":{"subset": "train", "action": [ 0 ,1, 113 ]},
"0002":{"subset": "train", "action": [ 0 ,1, 108 ]},
"0003":{"subset": "val", "action": [ 0 ,1, 102 ]},
"0004":{"subset": "val", "action": [ 0 ,1, 124 ]},
"0005":{"subset": "test", "action": [ 0 ,1, 52 ]}}

Assuming it follows the following format: 
vid_id :{"subset": "train/val/test", "action": [ word ,starting frame, ending frame ]}}

is that the correct way? because it prints len(dataset) = 0 
and I'm not sure why since the dir path is correct, the dataset is small only 6 files so far, is that why?

**Comment by shahd98gar** [comment]
is that work ?

**Comment by atheeraa** [comment]
> is that work ?

I'm not sure. I stopped working on it.
