### ISSUE TITLE
Some videos in asl2000.json not present in WLASL_v03.json

### ISSUE THREAD

**Issue by davidlainesv** [dxli94/WLASL#38]
**Describe the bug**
The following video id's in asl2000.json are not present in WLASL_v03.json.

**To Reproduce**
1. Go to 'WLASL_v03.json'
2. Search for any of the following video id's: 20065, 20138, 48251, 13422, 16096, 39347, 57839, 47639, 12209, 51153, 60721, 09500.
3. See video_id not found

**Expected behavior**
Video id's in asl2000.json should be described in WLASL_v03.json, too.

**Comments**
I first thought it could be that those videos are not available anymore and that would be the reason why those ids are not present in WLASL_v03.json. However, as an example, video_id = 09500 with url = https://elementalaslconcepts.weebly.com/uploads/2/4/4/5/24454483/larva.mov is available for download.

Why does this happen?

**Comment by dxli94** [comment]
These 12 videos are not used in the v0.3 release or in the reported experiments. Please feel safe to ignore.

Sorry about this confusion!
