### ISSUE TITLE
Dataset Size

### ISSUE THREAD

**Issue by imr555** [dxli94/WLASL#4]
This is not an issue strictly. We would like to know the size of the dataset so that when we download we can issue that much space in advance. 

Thanks in advance :)

**Comment by dxli94** [comment]
Raw videos are around 7Gb. If you can have 20Gb disk space available (extra for some intermediate processing), it should be fine. 

Before training the model, we first crop a square patch around the person and then resize to 256x256. At the end, we store these 256x256 videos on the disk, amounting to roughly 2Gb. 

If you encounter any download issue, please follow the README instructions and let me know.

**Comment by imr555** [comment]
Thank you very Much for the detailed answer. Hope you have a good day. :)
