### ISSUE TITLE
Which glosses are represented in WLASL100, 300 and 1000

### ISSUE THREAD

**Issue by FicekD** [dxli94/WLASL#40]
I can't seem to find which glosses are used in the subsets mentioned in your paper (WLASL100, WLASL300 and WLASL1000), the only information in the annotation file regarding data split is split between train/val/test sets. In the paper you mention "we select top-K glosses and organize them into four subsets". Did you use the first K glosses or what exactly does this mean?

**Comment by dxli94** [comment]
"Did you use the first K glosses" - yes, that's the way to go.

Also find info here:
https://github.com/dxli94/WLASL#constituting-subsets

**Comment by FicekD** [comment]
okay, thanks!
