### ISSUE TITLE
Prepare pose result for TGCN model

### ISSUE THREAD

**Issue by Tran-Nam** [dxli94/WLASL#44]
Hi, I want to prepare custom dataset for training TGCN model, but the preprocessing step is described not clear enough. 
```
We resize the resolution of all original video frames such that the diagonal size of the person bounding-box is 256 pixels
``` 
I check the origin file ```WLASL_v0.3.json```, get bbox value, calculate the diagonal size of this box, then calculate the resize ratio. After resize image, i draw the pose result but the keypoint is not correct. I also found that the bbox value in file ```asl100.json``` is the same regardless the video. 
Can you explain more detail about which steps you do in preprocessing?

**Comment by dxli94** [comment]
Hi,

Poses-TGCN is observed quite robust with respect to these preprocessing steps. I therefore suggest the following steps:
1. capture & collect your custom sign language videos;
2. use OpenPose to extract 2d keypoints from each frames;
3. checkout the dataloader for pose-TGCN to normalize poses and feed them into the model for training.

Detecting body boxes or resizing the video may not be necessary, as long as OpenPose can capture well the necessary keypoints.

Thanks.

**Comment by Tran-Nam** [comment]
As I see in your code, you normalize the coordinate by using function 2*(x-0.5) with x is coordinate of keypoints. I don't know if this operation scale them to [-1, 1] or not because the person image is not 256x256?

**Comment by dxli94** [comment]
Yes. They will be normalize to [-1, 1]. You may have a look at the dataloader for TGCN for more information.

Thanks!
