### ISSUE TITLE
Train_I3d.py

### ISSUE THREAD

**Issue by amna-ai** [dxli94/WLASL#46]
' No module named 'torch' ' . Whenever I try to run the train_i3d.py file, it shows this error. I have tried pip installing the modules. Although the modules do get installed, I also restart the kernel , but this error still comes up. If anyone can help me with it.
Waiting for the response.

**Comment by dxli94** [comment]
PyTorch is not properly installed. Likely it is not installed in your system paths.

**Comment by amna-ai** [comment]
One more thing, I don't have GPU so I commented all the cuda commands. Also when I ran train_i3d.py my laptop got stuck for so long that I had to force shut down it. This happened the second time to when I tried to run it again. Is it because of not having a gpu?

**Comment by dxli94** [comment]
Could be it's running out of RAM.
