### ISSUE TITLE
Running out of RAM while running preprocess.py

### ISSUE THREAD

**Issue by aaditya0702** [dxli94/WLASL#7]
Thank you for collecting such a large and comprehensive dataset. 
When I run the preprocess.py file after downloading videos(19342 of them), it gives this error- 

![image](https://user-images.githubusercontent.com/42470833/86442145-f2eb3b80-bd2a-11ea-860f-c657219fa93a.png)

It's only preprocessing 42 videos and then it runs out of RAM. I have an 8GB RAM on my computer so I'm not sure why it's happening.

**Comment by dxli94** [comment]
I could not reproduce the issue. Maybe you can trace the memory consumption to diagnose.

**Comment by aaditya0702** [comment]
I'm sorry, it seems to be because I'm using a GPU which is using a large amount of RAM.
