### ISSUE TITLE
Request To Obtain The Missing Videos (haved submitted my missing.txt file)

### ISSUE THREAD

**Issue by davimedio01** [dxli94/WLASL#70]
I hope this message finds you well!

As part of my research in master degree, I am intending to use the WL-ASL database, which has been an invaluable resource in various researches. However, I have encountered an issue with certain videos that I have been unable to download from the database...

I ask for your help to obtain these lost videos, as I can see in the “Requesting Missing / Pre-processed Videos” section in the repository, **after the 7 days of request after sending the forms. The "missing.txt" file, which contains all the videos that cannot be downloaded, is attached below. My e-mail is davi.neves@unesp.br.**

[missing.txt](https://github.com/dxli94/WLASL/files/15444786/missing.txt)

Thank you very much for your time and consideration!

**Comment by JChaloton** [comment]
@davimedio01 Greeting. I have generated my missing.txt and the numbers of the missing video files are the same as yours. Would you mind sharing the link with me? My email is t112618403@ntut.org.tw

Thank you in advance for your consideration!
